// <auto-generated />
using System;
using ECommerceWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721100342_AddCategoryIconClass")]
    partial class AddCategoryIconClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerceWeb.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("UserID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerceWeb.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"), 1L, 1);

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "CPU",
                            Description = "Bộ vi xử lý trung tâm",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "VGA",
                            Description = "Card đồ họa",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "RAM",
                            Description = "Bộ nhớ truy cập ngẫu nhiên",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "SSD",
                            Description = "Ổ cứng thể rắn",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Màn hình",
                            Description = "Màn hình máy tính",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Bàn phím",
                            Description = "Bàn phím máy tính",
                            IconClass = "bi-cpu"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Chuột",
                            Description = "Chuột máy tính",
                            IconClass = "bi-cpu"
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ChatMessageID");

                    b.HasIndex("UserID");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("ECommerceWeb.Models.EmailLog", b =>
                {
                    b.Property<int>("EmailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailID"), 1L, 1);

                    b.Property<string>("EmailContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Favorite", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"), 1L, 1);

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("UserID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ECommerceWeb.Models.MembershipTier", b =>
                {
                    b.Property<int>("TierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierID"), 1L, 1);

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TierID");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            TierID = 1,
                            ColorHex = "#e0e0e0",
                            IconClass = "fa-solid fa-user",
                            MinPoints = 0,
                            TierName = "Tech-Newie"
                        },
                        new
                        {
                            TierID = 2,
                            ColorHex = "#f5c3a6",
                            IconClass = "fa-solid fa-star",
                            MinPoints = 300,
                            TierName = "Tech-Member"
                        },
                        new
                        {
                            TierID = 3,
                            ColorHex = "#f5d17e",
                            IconClass = "fa-solid fa-crown",
                            MinPoints = 1500,
                            TierName = "Tech-VIP"
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.NewsArticle", b =>
                {
                    b.Property<int>("NewsArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsArticleID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsArticleID");

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            NewsArticleID = 1,
                            Category = "Kinh nghiệm",
                            Excerpt = "Lựa chọn card đồ họa luôn là câu hỏi đau đầu nhất khi build PC. Cùng tìm hiểu cách chọn VGA tối ưu...",
                            ImageUrl = "https://cdn2.fptshop.com.vn/unsafe/1920x0/filters:format(webp):quality(75)/nen_mua_card_man_hinh_nao_de_choi_game_2026_thumb_3323eef885.png",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hướng dẫn chọn Card Màn Hình (VGA) phù hợp cho nhu cầu chơi game 2026"
                        },
                        new
                        {
                            NewsArticleID = 2,
                            Category = "Tin tức công nghệ",
                            Excerpt = "Đánh giá chi tiết hiệu năng nâng cấp của dòng xử lý mới nhất từ Intel và xem liệu nó có đáng để bạn xuống...",
                            ImageUrl = "https://cdn-media.sforum.vn/storage/app/media/trannghia/trannghia/1/intel-core-series-3-wildcat-lake-01.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intel ra mắt dòng CPU thế hệ mới: Có thực sự đáng nâng cấp?"
                        },
                        new
                        {
                            NewsArticleID = 3,
                            Category = "Thủ thuật",
                            Excerpt = "Những tinh chỉnh đơn giản trên hệ điều hành giúp tắt các dịch vụ không cần thiết, giải phóng RAM và tăng...",
                            ImageUrl = "https://kimlongcenter.com/upload/image/Thu%20Thuat/C%C3%A1ch%20t%E1%BB%91i%20%C6%B0u%20%C4%91%E1%BB%83%20ch%C6%A1i%20game%20m%C6%B0%E1%BB%A3t%20h%C6%A1n/c%C3%A1ch-t%E1%BB%91i-%C6%B0u-%C4%91%E1%BB%83-ch%C6%A1i-game-m%C6%B0%E1%BB%A3t-h%C6%A1n.jpg",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "5 Cách tối ưu hóa hệ điều hành để chơi game mượt mà hơn"
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.HasIndex("VoucherID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerceWeb.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"), 1L, 1);

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"), 1L, 1);

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ECommerceWeb.Models.PointsHistory", b =>
                {
                    b.Property<int>("PointsHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointsHistoryID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("PointsChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PointsHistoryID");

                    b.HasIndex("UserID");

                    b.ToTable("PointsHistories");
                });

            modelBuilder.Entity("ECommerceWeb.Models.PrebuiltPc", b =>
                {
                    b.Property<int>("PrebuiltPcID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrebuiltPcID"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrebuiltPcID");

                    b.ToTable("PrebuiltPcs");

                    b.HasData(
                        new
                        {
                            PrebuiltPcID = 1,
                            DisplayOrder = 1,
                            ImageUrl = "https://www.tncstore.vn/media/product/11995-pc-gaming-nova-a5070-bl--3-.jpg",
                            IsBestSeller = false,
                            Name = "Budget King",
                            Price = 15990000m
                        },
                        new
                        {
                            PrebuiltPcID = 2,
                            DisplayOrder = 2,
                            ImageUrl = "https://mygear.io.vn/media/product/7830-pc-gaming-cyberpower-rtx-5060-i5-12400f-u-1.png",
                            IsBestSeller = true,
                            Name = "Mid-Range Beast",
                            Price = 28500000m
                        },
                        new
                        {
                            PrebuiltPcID = 3,
                            DisplayOrder = 3,
                            ImageUrl = "https://breunor.com/cdn/shop/files/rossa_4649c942-d446-4369-9cc6-db35e9026377.jpg?v=1771404016&width=1024",
                            IsBestSeller = false,
                            Name = "Ultimate Performance",
                            Price = 95000000m
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.PrebuiltPcSpec", b =>
                {
                    b.Property<int>("PrebuiltPcSpecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrebuiltPcSpecID"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("PrebuiltPcID")
                        .HasColumnType("int");

                    b.Property<string>("SpecText")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PrebuiltPcSpecID");

                    b.HasIndex("PrebuiltPcID");

                    b.ToTable("PrebuiltPcSpecs");

                    b.HasData(
                        new
                        {
                            PrebuiltPcSpecID = 1,
                            DisplayOrder = 1,
                            PrebuiltPcID = 1,
                            SpecText = "Intel Core i5-12400F"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 2,
                            DisplayOrder = 2,
                            PrebuiltPcID = 1,
                            SpecText = "RAM 16GB DDR4 3200MHz"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 3,
                            DisplayOrder = 3,
                            PrebuiltPcID = 1,
                            SpecText = "VGA RTX 3060 12GB"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 4,
                            DisplayOrder = 4,
                            PrebuiltPcID = 1,
                            SpecText = "SSD 500GB NVMe"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 5,
                            DisplayOrder = 1,
                            PrebuiltPcID = 2,
                            SpecText = "Intel Core i5-13600K"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 6,
                            DisplayOrder = 2,
                            PrebuiltPcID = 2,
                            SpecText = "RAM 32GB DDR5 5600MHz"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 7,
                            DisplayOrder = 3,
                            PrebuiltPcID = 2,
                            SpecText = "VGA RTX 4060 Ti 8GB"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 8,
                            DisplayOrder = 4,
                            PrebuiltPcID = 2,
                            SpecText = "SSD 1TB NVMe Gen4"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 9,
                            DisplayOrder = 1,
                            PrebuiltPcID = 3,
                            SpecText = "Intel Core i9-14900K"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 10,
                            DisplayOrder = 2,
                            PrebuiltPcID = 3,
                            SpecText = "RAM 64GB DDR5 6000MHz"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 11,
                            DisplayOrder = 3,
                            PrebuiltPcID = 3,
                            SpecText = "VGA RTX 4090 24GB"
                        },
                        new
                        {
                            PrebuiltPcSpecID = 12,
                            DisplayOrder = 4,
                            PrebuiltPcID = 3,
                            SpecText = "SSD 2TB NVMe Gen4"
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<int?>("CategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "CPU Intel Core i5-13400F 10 nhân 16 luồng, tốc độ 2.5GHz, hỗ trợ RAM DDR5, socket LGA1700, không tích hợp đồ họa.",
                            ImageUrl = "https://cdn2.cellphones.com.vn/x/media/catalog/product/c/p/cpu-intel-core-i5-13400f-tray_2_.png",
                            IsNew = false,
                            OldPrice = 4690000m,
                            Price = 4290000m,
                            ProductName = "CPU Intel Core i5-13400F",
                            Quantity = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 32
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Card đồ họa Gigabyte RTX 4060 Ti Super 8GB GDDR6, 128-bit, hỗ trợ DLSS 3, Ray Tracing, xuất hình 4K.",
                            ImageUrl = "https://product.hstatic.net/200000722513/product/9899_e1b98e8a5f63e754f57497ecf79488f5_292572e5779f431098d1236845acc095_fb8c3e65086e43388656e5b4ea0c138a_master.jpg",
                            IsNew = true,
                            OldPrice = 11490000m,
                            Price = 9990000m,
                            ProductName = "VGA GIGABYTE GeForce RTX 4060 Ti Super",
                            Quantity = 0,
                            Rating = 4.9000000000000004,
                            ReviewCount = 18
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RAM Kingston Fury Beast 16GB (1x16GB) DDR5 6000MHz, CL40, hỗ trợ XMP 3.0, tản nhiệt màu đen.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyHfoa5rzla1de4bt8URqa5v1qS-QumqoFRGh-FauusKr_2PsO1d8qleM&s=10",
                            IsNew = true,
                            Price = 1590000m,
                            ProductName = "RAM Kingston Fury Beast 16GB DDR5 6000MHz",
                            Quantity = 0,
                            Rating = 4.7000000000000002,
                            ReviewCount = 45
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 4,
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SSD Samsung 990 PRO 2TB, PCIe 4.0 x4, tốc độ đọc lên đến 7450 MB/s, ghi 6900 MB/s, hỗ trợ công nghệ V-NAND và tản nhiệt hiệu quả.",
                            ImageUrl = "https://bizweb.dktcdn.net/thumb/1024x1024/100/329/122/products/ssd-samsung-990-pro-pcie-gen-4-0-x4-nvme-with-heatsink-905954f6-13ab-4baf-8150-e682df092cb6.jpg?v=1696582447337",
                            IsNew = true,
                            OldPrice = 5290000m,
                            Price = 4850000m,
                            ProductName = "SSD Samsung 990 PRO 2TB PCIe NVMe 4.0x4",
                            Quantity = 0,
                            Rating = 5.0,
                            ReviewCount = 27
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 5,
                            CreatedAt = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Màn hình LG UltraGear 27 inch OLED, độ phân giải 2560x1440, tần số quét 240Hz, thời gian phản hồi 0.03ms, hỗ trợ HDR10.",
                            ImageUrl = "https://cdn2.cellphones.com.vn/x/media/catalog/product/m/a/man-hinh-lg-ultragear-oled-27gr95qe-b-27-inch-1.png",
                            IsNew = true,
                            Price = 22990000m,
                            ProductName = "Màn hình LG UltraGear 27GR95QE-B 27\" OLED",
                            Quantity = 0,
                            Rating = 4.9000000000000004,
                            ReviewCount = 12
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 6,
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bàn phím cơ Logitech G Pro X với switch GX Brown tùy chỉnh, đèn RGB, kích thước nhỏ gọn, chuyên cho game thủ.",
                            ImageUrl = "https://www.logitechg.com/content/dam/gaming/en/products/pro-x-keyboard/pro-x-keyboard-gallery-1.png",
                            IsNew = true,
                            Price = 2490000m,
                            ProductName = "Bàn phím cơ Logitech G Pro X",
                            Quantity = 0,
                            Rating = 4.5999999999999996,
                            ReviewCount = 20
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 7,
                            CreatedAt = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuột gaming Logitech G502 HERO với cảm biến HERO 25K, 11 nút lập trình, dây cáp, đèn RGB, trọng lượng có thể điều chỉnh.",
                            ImageUrl = "https://product.hstatic.net/200000722513/product/10001_01736316d2b443d0838e5a0741434420_master.png",
                            IsNew = true,
                            OldPrice = 1590000m,
                            Price = 1290000m,
                            ProductName = "Chuột gaming Logitech G502 HERO",
                            Quantity = 0,
                            Rating = 4.7999999999999998,
                            ReviewCount = 35
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.Shipping", b =>
                {
                    b.Property<int>("ShippingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingID"), 1L, 1);

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("ShippingCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ShippingID");

                    b.HasIndex("OrderID");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DistrictNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OpenHours")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreID = 1,
                            Address = "123 Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
                            AddressNormalized = "123 xuan thuy, dich vong hau, cau giay, ha noi",
                            District = "Cầu Giấy",
                            DistrictNormalized = "cau giay",
                            IsActive = true,
                            Latitude = 21.036799999999999,
                            Longitude = 105.78270000000001,
                            Name = "PC Master - Cầu Giấy",
                            NameNormalized = "pc master - cau giay",
                            OpenHours = "08:00 - 21:00",
                            Phone = "024 1234 5678"
                        },
                        new
                        {
                            StoreID = 2,
                            Address = "45 Thái Hà, Trung Liệt, Đống Đa, Hà Nội",
                            AddressNormalized = "45 thai ha, trung liet, dong da, ha noi",
                            District = "Đống Đa",
                            DistrictNormalized = "dong da",
                            IsActive = true,
                            Latitude = 21.0136,
                            Longitude = 105.82129999999999,
                            Name = "PC Master - Đống Đa",
                            NameNormalized = "pc master - dong da",
                            OpenHours = "08:30 - 21:30",
                            Phone = "024 8765 4321"
                        },
                        new
                        {
                            StoreID = 3,
                            Address = "78 Lê Thanh Nghị, Bách Khoa, Hai Bà Trưng, Hà Nội",
                            AddressNormalized = "78 le thanh nghi, bach khoa, hai ba trung, ha noi",
                            District = "Hai Bà Trưng",
                            DistrictNormalized = "hai ba trung",
                            IsActive = true,
                            Latitude = 21.002099999999999,
                            Longitude = 105.8437,
                            Name = "PC Master - Hai Bà Trưng",
                            NameNormalized = "pc master - hai ba trung",
                            OpenHours = "08:00 - 21:00",
                            Phone = "024 2468 1357"
                        },
                        new
                        {
                            StoreID = 4,
                            Address = "234 Quang Trung, Hà Đông, Hà Nội",
                            AddressNormalized = "234 quang trung, ha dong, ha noi",
                            District = "Hà Đông",
                            DistrictNormalized = "ha dong",
                            IsActive = true,
                            Latitude = 20.971699999999998,
                            Longitude = 105.777,
                            Name = "PC Master - Hà Đông",
                            NameNormalized = "pc master - ha dong",
                            OpenHours = "08:30 - 21:30",
                            Phone = "024 1357 2468"
                        },
                        new
                        {
                            StoreID = 5,
                            Address = "56 Điện Biên Phủ, Phường 15, Bình Thạnh, TP. Hồ Chí Minh",
                            AddressNormalized = "56 dien bien phu, phuong 15, binh thanh, tp. ho chi minh",
                            District = "Bình Thạnh",
                            DistrictNormalized = "binh thanh",
                            IsActive = true,
                            Latitude = 10.803100000000001,
                            Longitude = 106.715,
                            Name = "PC Master - Bình Thạnh",
                            NameNormalized = "pc master - binh thanh",
                            OpenHours = "08:00 - 21:30",
                            Phone = "028 3512 6789"
                        },
                        new
                        {
                            StoreID = 6,
                            Address = "88 Nguyễn Huệ, Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                            AddressNormalized = "88 nguyen hue, ben nghe, quan 1, tp. ho chi minh",
                            District = "Quận 1",
                            DistrictNormalized = "quan 1",
                            IsActive = true,
                            Latitude = 10.775600000000001,
                            Longitude = 106.7025,
                            Name = "PC Master - Quận 1",
                            NameNormalized = "pc master - quan 1",
                            OpenHours = "08:00 - 22:00",
                            Phone = "028 3822 4567"
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.TierBenefit", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TierID")
                        .HasColumnType("int");

                    b.HasKey("BenefitID");

                    b.HasIndex("TierID");

                    b.ToTable("TierBenefits");

                    b.HasData(
                        new
                        {
                            BenefitID = 1,
                            Description = "Tặng voucher 50K khi lên hạng",
                            IconClass = "fa-solid fa-ticket",
                            TierID = 2
                        },
                        new
                        {
                            BenefitID = 2,
                            Description = "Giảm thêm 0.5% khi mua linh kiện PC",
                            IconClass = "fa-solid fa-gift",
                            TierID = 2
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TierID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("TierID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceWeb.Models.UserVoucher", b =>
                {
                    b.Property<int>("UserVoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserVoucherID"), 1L, 1);

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsedInOrderID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("VoucherID")
                        .HasColumnType("int");

                    b.HasKey("UserVoucherID");

                    b.HasIndex("VoucherID");

                    b.HasIndex("UserID", "VoucherID")
                        .IsUnique();

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("VoucherID");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            VoucherID = 1,
                            Code = "WELCOME50",
                            Description = "Chào mừng thành viên mới",
                            DiscountType = "Fixed",
                            DiscountValue = 50000m,
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MinOrderValue = 200000m,
                            Title = "Giảm 50.000đ",
                            UsedCount = 0
                        },
                        new
                        {
                            VoucherID = 2,
                            Code = "SALE10",
                            Description = "Áp dụng cho đơn hàng từ 500.000đ",
                            DiscountType = "Percent",
                            DiscountValue = 10m,
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 100000m,
                            MinOrderValue = 500000m,
                            Title = "Giảm 10%",
                            UsageLimit = 1000,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("ECommerceWeb.Models.WarrantyTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarrantyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarrantyTickets");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Cart", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.CartItem", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceWeb.Models.ChatMessage", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.EmailLog", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Favorite", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Feedback", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Order", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherID");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ECommerceWeb.Models.OrderDetail", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Payment", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerceWeb.Models.PointsHistory", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceWeb.Models.PrebuiltPcSpec", b =>
                {
                    b.HasOne("ECommerceWeb.Models.PrebuiltPc", "PrebuiltPc")
                        .WithMany("Specs")
                        .HasForeignKey("PrebuiltPcID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrebuiltPc");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Product", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Shipping", b =>
                {
                    b.HasOne("ECommerceWeb.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerceWeb.Models.TierBenefit", b =>
                {
                    b.HasOne("ECommerceWeb.Models.MembershipTier", "Tier")
                        .WithMany("Benefits")
                        .HasForeignKey("TierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ECommerceWeb.Models.User", b =>
                {
                    b.HasOne("ECommerceWeb.Models.MembershipTier", "Tier")
                        .WithMany("Users")
                        .HasForeignKey("TierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ECommerceWeb.Models.UserVoucher", b =>
                {
                    b.HasOne("ECommerceWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommerceWeb.Models.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceWeb.Models.MembershipTier", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ECommerceWeb.Models.PrebuiltPc", b =>
                {
                    b.Navigation("Specs");
                });

            modelBuilder.Entity("ECommerceWeb.Models.Voucher", b =>
                {
                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
